# Generated by Django 4.2.6 on 2023-10-30 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='periodicity',
            field=models.CharField(choices=[(datetime.timedelta(days=1), 'Раз в день'), (datetime.timedelta(days=7), 'Раз в неделю'), (datetime.timedelta(days=30, seconds=43200), 'Раз в месяц')], max_length=50, verbose_name='периодичность'),
        ),
    ]
