# Generated by Django 4.2.6 on 2023-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_mailingsettings_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='periodicity',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], max_length=50, verbose_name='периодичность'),
        ),
    ]
