# Generated by Django 4.2.6 on 2023-10-28 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_log_client_alter_log_mailing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.mailingsettings', verbose_name='рассылка'),
        ),
    ]
