# Generated by Django 4.2.6 on 2023-10-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_alter_message_mailing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='distribution.mailingsettings', verbose_name='рассылка'),
        ),
    ]
